name: Build Server and Client

on:
  push:
    branches:
      - dev_server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          cd server
          npm install
          cd ../client
          npm install

      - name: Build Server
        run: |
          cd server
          npm run build

      - name: Build Client
        run: |
          cd client
          npm run build

      - name: Create Test-TS Directory
        run: |
          mkdir -p test-ts

      - name: Copy Server Dist to Test-TS
        run: |
          cp -r server/dist/* test-ts/server

      - name: Copy Server Package.json to Test-TS
        run: |
          cp server/package.json test-ts/server

      - name: Copy Client Dist to Test-TS
        run: |
          cp -r client/dist test-ts/client

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-ts
          path: |
            test-ts
