name: Build and Deploy Server and Client

on:
  push:
    branches:
      - dev_server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          cd server
          npm install
          cd ../client
          npm install

      - name: Build Server
        run: |
          cd server
          npm run build

      - name: Build Client
        run: |
          cd client
          npm run build

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-ts
          path: |
            server/dist 
            client/dist
            server/package.json

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-ts
          path: test-ts

      - name: Push to Target Repository
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          git config --global user.email "mansu7802@gmail.com"
          git config --global user.name "suman7802"
          git config --global url.'https://$GITHUB_TOKEN:@github.com/'.insteadOf 'https://github.com/'
          
          git clone https://github.com/suman7802/test-ts2.git target-repo
          cd target-repo

          git checkout -b main || git checkout main

          cp -r ../test-ts/* .

          git add .
          git commit -m "Copy artifacts from source-repo"
          git push origin main