name: Deploy Server and Client

# on:
#   workflow_run:
#     workflows: ['Build Server and Client']
#     types:
#       - completed
on:
  push:
    branches:
      - dev_server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-ts
          path: test-ts

      - name: Push to Target Repository
        run: |
          git config --global user.email "mansu7802@gmail.com"
          git config --global user.name "suman7802"
          git clone https://github.com/suman7802/test-ts2.git target-repo

          cd target-repo

          git checkout -b main || git checkout main

          cp -r ../test-ts/* .

          git add .
          git commit -m "Copy artifacts from source-repo"
          git push origin main
